//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class note
    {
        public int noteId { get; set; }
        public string noteName { get; set; }
        public string description { get; set; }
        public Nullable<int> usrId { get; set; }
    
        public virtual user user { get; set; }
    }
}
